Add job log visibilitiy
DistributedProofreaders/dproofreaders pull request #1236
Opened 2024-06-12 01:43 UTC by cpeel

Did you know we have a job log? Me neither! That's because we currently log to it in exactly two scripts and have zero way to view it. This gives SAs the ability to see the table and adds an index on the timestamp.

It removes a useless "MIDDLE" message from automodify.

https://www.pgdp.org/~cpeel/c.branch/job-log-visibilitiy/

This is related to https://github.com/DistributedProofreaders/dproofreaders/issues/1233

2024-06-12 02:17 UTC, chrismiceli approved these changes

2024-06-12 07:50 UTC, srjfoo approved these changes
I like it!

I don't know if this is the time or place to do it, but is it possible to have some documentation on valid filenames and events. I guessed that END would be. (😁)

2024-06-12 09:37 UTC, 70ray requested changes

2024-06-12 09:37 UTC, 70ray commented on tools/site_admin/show_job_log.php
> +    echo "<td>" . date("Y-h-d H:i:s", $row["tracetime"]) . "</td>";
Should be Y-m-d

2024-06-13 01:14 UTC, cpeel commented on tools/site_admin/show_job_log.php
> +    echo "<td>" . date("Y-h-d H:i:s", $row["tracetime"]) . "</td>";
Good catch - fixed!

2024-06-13 01:16 UTC, cpeel commented
> I don't know if this is the time or place to do it, but is it possible to have some documentation on valid filenames and events. 

I've changed 'Filename' to 'Job' in the last commit as I anticipate us using it in a broader sense. The "event"s are very ad hoc right now. So "not yet but there's work to be done in this area".

2024-06-13 01:20 UTC, srjfoo approved these changes

2024-06-14 07:08 UTC, 70ray approved these changes

2024-06-14 23:21 UTC, merged