Add endpoint for languages with dictioaries
DistributedProofreaders/dproofreaders pull request #1406
Opened 2024-12-24 16:32 UTC by 70ray

2024-12-24 21:31 UTC, 70ray commented on api/v1_docs.inc
> +    asort($dict_list);
Should be sort not asort.

2024-12-25 02:23 UTC, chrismiceli approved these changes

2024-12-25 15:55 UTC, 70ray commented
Sandbox updated.

2025-01-09 06:29 UTC, jchaffraix approved these changes
Nit: typo in the description "dictioaries"

2025-02-09 01:26 UTC, cpeel commented
I rebased this to resolve the merge conflict.

2025-02-09 01:29 UTC, cpeel requested changes
I've waffled on this for a bit as this will be a bit of a loner endpoint. Ultimately I agree that grouping it with docs makes sense rather than creating a single file just for this one function.

It needs to be added to `dp-openapi.yaml` and I had a couple of other small comments.

2025-02-09 01:29 UTC, cpeel commented on api/v1_docs.inc
> +function api_v1_dictionaries(string $method, array $data, array $query_params): array
```suggestion
/** @param array<string, string|string[]> $query_params */
function api_v1_dictionaries(string $method, array $data, array $query_params): array
```

2025-02-09 01:29 UTC, cpeel commented on api/v1_docs.inc
> +    $dict_list = array_values(get_languages_with_dictionaries());
I think if we returned the associated array directly from `get_languages_with_dictionaries()` instead of just the language this would be a more flexible endpoint.

2025-02-09 12:29 UTC, 70ray commented on api/v1_docs.inc
> +    $dict_list = array_values(get_languages_with_dictionaries());
Done this and changed to asort because sort would re-assign keys. These keys could be useful to send back to simplify finding the aspell dictionaries although the code currently has to re-discover them from the language names.

2025-02-09 14:56 UTC, cpeel approved these changes

2025-02-09 18:32 UTC, cpeel commented on api/v1_docs.inc
> +    $dict_list = array_values(get_languages_with_dictionaries());
> Isn't this premature optimization? in the sense of sending extra information that we don't need but could possibly be useful in the future.

It is, but when designing APIs we sometimes need to do that, because after we publish them we can't change them in ways that break. So having a little extra data here is going to mean we don't have to create a v2 of the endpoint to add it later.

2025-02-09 18:35 UTC, cpeel commented
Ray's sandbox isn't up-to-date so I published it under mine. This is testable with:
```bash
export API_KEY=review
curl -i -H "Accept: application/json" -H "X-API-KEY: $API_KEY" \
    -X GET "https://www.pgdp.org/~cpeel/c.branch/api_dics/api/v1/dictionaries"
```

2025-02-09 19:03 UTC, jchaffraix approved these changes

2025-02-09 19:37 UTC, 70ray commented
> Ray's sandbox isn't up-to-date so I published it under mine. ...
Thanks Casey, I forgot this. I've updated it now in case it's useful.

2025-02-09 20:31 UTC, srjfoo approved these changes

2025-02-09 22:32 UTC, cpeel commented
Rebased again to resolve the merge conflict. Will merge this in once it passes CI.

2025-02-09 22:33 UTC, merged