Give user a page they've never seen if possible
DistributedProofreaders/dproofreaders pull request #415
Opened 2020-09-11 16:54 UTC by cpeel

PROD and TEST have `$preceding_proofer_restriction` set to `not_immediately_preceding`, which means that when a proofreader hits "Start Proofreading" or "Save and Done and Proofread Next" we will only give them pages they have not proofed in the prior round. The value can also be set to `not_previously_proofed` which will only give them pages they have never proofed before.

[Task 1137](https://www.pgdp.net/c/tasks.php?action=show&task_id=1137) requests that even if the site is set to `not_immediately_preceding`, we first try to see if we can satisfy `not_previously_proofed` and give them a page they have never seen before. If we can't we fall back to `not_immediately_preceding`. That seems very reasonable and this MR implements that logic.

This is testable in the [get-best-page](https://www.pgdp.org/~cpeel/c.branch/get-best-page/) sandbox.

2020-09-12 06:36 UTC, srjfoo approved these changes
Looks good.

2020-09-12 15:13 UTC, jmdyck requested changes
I have an alternative approach that I think it would be easier to understand. It would also be slightly more efficient, in that it avoids the possibility of needing 2 queries to get the next page. Specifically, for 'not_immediately_preceding', specify an `$order` that puts never-seen pages before previously-seen pages (with a secondary sort on `image`). So if there are any never-seen pages, the SELECT will return the next of those, and if there aren't, it'll return the next previously-seen page (if any).

The 'not_previously_proofed' case is already (basically) constructing the never-seen condition (though for WHERE rather than ORDER), so you could pull that code out either as a preliminary or a utility function.

(And you'd need to move the mentor-specific chunk later, so that its `$order` overrides the one from 'not_immediately_preceding'.)

(BTW, I had a long think about the race condition mentioned in the comment before `$dbQuery`, as I thought it might be entangled in how this task should be implemented, but eventually decided that it's probably orthogonal.)

2020-09-12 17:40 UTC, cpeel commented
> I have an alternative approach that I think it would be easier to understand.

Interesting, because to me that approach seems much more difficult to understand from a code perspective. Currently we have two modes that are easy to conceptualize what they do and we can reuse the modes in understandable ways. Making the already-complex `not_immediately_preceding` even more complex seems like a step in the wrong direction.

I see the value in having one query instead of two, but I don't think making the code more difficult to understand and maintain is worth the return.

2020-09-13 13:50 UTC, 70ray reviewed
I suppose, in principle, it would be better to do something about the race condition mentioned by jmdyck before doing this. But that is probably difficult and it does not seem to be a problem in practice but it could be borne in mind for the api version of this part of the system.

I approve of Casey's wish to use the simplest possible code.

Wouldn't the usual convention put "get_available_page" first?

2020-09-13 15:56 UTC, cpeel commented
> I suppose, in principle, it would be better to do something about the race condition mentioned by jmdyck before doing this. But that is probably difficult and it does not seem to be a problem in practice but it could be borne in mind for the api version of this part of the system.

The API to do page checkouts would use this same function. I feel pretty confident we can solve this with some sensible DB locking but don't feel like we need to figure this out right now.

> Wouldn't the usual convention put "get_available_page" first?

The code is all over the place on if dependent functions come first or second. I did it this way to minimize the diff, not because I think it's particularly better or worse order-wise.

2020-09-13 19:24 UTC, 70ray approved these changes

2020-09-17 22:40 UTC, merged